# Week 2 - Data Analysis
#### Part 1
### Notebook created by Jonathan Penava
By the end of this lesson you should be able to read in a data set from a CSV file into a DataFrame, and manipulate that DataFrame.

## Overview
- <span style="color:red;">NumPy</span>
- Pandas
- Data Frames
- Reading CSV

### NumPy

In this part we want to look at NumPy arrays and some functionality.  This is the first step towards building Data Frames. <br>

Additional resources on NumPy:</br>
<a href="https://numpy.org/">NumPy</a></br>
</br>
What is NumPy?</br>
NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more. </br> (Copied from <a href="https://numpy.org/doc/stable/">NumPy Documentation</a>)

In [2]:
import numpy as np   #Import the NumPy library

In [4]:
newList = [1,2,3]    #Python list

We can create a NumPy array from a Python list

In [5]:
np.array(newList)    #NumPy array

array([1, 2, 3])

#### Some Built In NumPy Functions

In [6]:
np.arange(0,10)    #Generate an array from 0-9

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.arange(0,11,2)   #Generate an array from 0-10 step by 2

array([ 0,  2,  4,  6,  8, 10])

In [3]:
np.random.rand(10)   #Generate an array size 10 of random numbers from 0-1

array([0.34439034, 0.83447021, 0.82375739, 0.99190468, 0.49926998,
       0.66226369, 0.56135336, 0.51260664, 0.97638333, 0.89738519])

In [4]:
np.random.rand(10)*10   #Generate an array like above but from 0-10

array([1.53767939, 4.40016303, 9.12304434, 8.12822483, 5.26862474,
       1.31896243, 2.68854343, 4.53697888, 3.57658248, 3.89959059])

In [11]:
np.random.rand(4,4)   #Generate a 2 dimensional array of size 4 by 4

array([[0.94199409, 0.71141818, 0.66156486, 0.55748869],
       [0.16711001, 0.10709477, 0.26599061, 0.68141406],
       [0.32422406, 0.63452552, 0.04267148, 0.34965264],
       [0.574772  , 0.45827623, 0.77994706, 0.97590426]])

In [12]:
np.random.randint(1,100,10)   #Generate an integer array from 1-100 of size 10

array([33, 85, 87, 98, 19, 37, 31, 71, 24, 69], dtype=int32)

In [7]:
myIntArray = np.random.randint(1,100,10)
myIntArray

array([83, 61, 71, 35, 77, 58, 48, 24, 59, 94], dtype=int32)

In [8]:
myIntArray.max()  #The max value in the array  

np.int32(94)

In [9]:
myIntArray.argmax()  #The index of the max value

np.int64(9)

In [10]:
myIntArray.min()  #The minimum value

np.int32(24)

In [11]:
myIntArray.argmin()  #The index of the min value

np.int64(7)

In [18]:
myIntArray[3]  #The value at index 3

np.int32(32)

In [19]:
myIntArray[2:5]  #The values at index 2-4

array([15, 32, 50], dtype=int32)

There are a lot more built in commands for NumPy.  I encourage you to explore on your own.  You can find additional resources at https://numpy.org/doc/stable/